 server:
  port: 8080 # 伺服器的port號

 spring:
  h2:
    console:
      enabled: true
      settings: 
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:howtolose # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: group15 # database 用戶名
    password:  # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none