version: '2'
services:
  web:
    # image: tinclaire225/howtolose-frontend
    image: h2l-proxy3
    ports:
      - 80
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 2
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:80"
  backend:
    image: tinclaire225/howtolose-backend
    ports:
      - 8080
    deploy:
      mode: replicated
      replicas: 2
    # container_name: backend